/**
 * 核心像素精灵数据定义
 * 所有精灵使用 PixelMap 格式（二维颜色数组）
 * 颜色用 #RRGGBB，透明用 0
 */

import type { PixelMap } from './types';

// ==================== 颜色常量 ====================

// 皮肤与角色
const SKIN = '#FFCC99';
const HAIR = '#4A2500';
const HAT = '#8B4513';
const HAT_LIGHT = '#A0652F';
const EYE = '#000000';
const MOUTH = '#FF6666';
const SHIRT = '#4169E1';
const SHIRT_DARK = '#2B4DA0';
const PANTS = '#1E3A5F';
const BOOT = '#5C3317';
const WHITE = '#FFFFFF';

// 矿物
const GOLD = '#FFD700';
const GOLD_LIGHT = '#FFF8B0';
const GOLD_DARK = '#DAA520';
const DIAMOND_CLR = '#00FFFF';
const DIAMOND_LIGHT = '#B0FFFF';
const DIAMOND_DARK = '#0099CC';
const STONE = '#808080';
const STONE_LIGHT = '#A0A0A0';
const STONE_DARK = '#606060';
const BOMB_BODY = '#333333';
const BOMB_FUSE = '#FF4400';
const BOMB_SPARK = '#FFFF00';
const BAG = '#B8860B';
const BAG_TIE = '#8B0000';
const BONE = '#F5F5DC';
const BONE_DARK = '#D2C6A5';

// 钩爪
const HOOK = '#C0C0C0';
const HOOK_DARK = '#808080';
const ROPE = '#DEB887';

// ==================== 角色精灵 ====================

/** 矿工-待机 (16x16) - 坐姿，微微前倾 */
export const MINER_IDLE: PixelMap = [
  [0, 0, 0, 0, 0, HAT, HAT, HAT, HAT, HAT, HAT, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, HAT, HAT, HAT_LIGHT, HAT_LIGHT, HAT_LIGHT, HAT, HAT, HAT, 0, 0, 0, 0],
  [0, 0, 0, 0, HAT, HAT, HAT, HAT, HAT, HAT, HAT, HAT, 0, 0, 0, 0],
  [0, 0, 0, 0, HAIR, HAIR, HAIR, HAIR, HAIR, HAIR, HAIR, HAIR, 0, 0, 0, 0],
  [0, 0, 0, 0, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, 0, 0, 0, 0],
  [0, 0, 0, 0, SKIN, EYE, WHITE, SKIN, SKIN, WHITE, EYE, SKIN, 0, 0, 0, 0],
  [0, 0, 0, 0, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, 0, 0, 0, 0],
  [0, 0, 0, 0, SKIN, SKIN, MOUTH, MOUTH, SKIN, SKIN, SKIN, SKIN, 0, 0, 0, 0],
  [0, 0, 0, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, 0, 0, 0],
  [0, 0, 0, SHIRT, SHIRT, SHIRT_DARK, SHIRT, SHIRT, SHIRT, SHIRT_DARK, SHIRT, SHIRT, SHIRT, 0, 0, 0],
  [0, 0, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, 0, 0],
  [0, 0, 0, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, 0, 0, 0],
  [0, 0, 0, 0, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, 0, 0, 0, 0],
  [0, 0, 0, 0, PANTS, PANTS, 0, 0, 0, 0, PANTS, PANTS, 0, 0, 0, 0],
  [0, 0, 0, 0, PANTS, PANTS, 0, 0, 0, 0, PANTS, PANTS, 0, 0, 0, 0],
  [0, 0, 0, 0, BOOT, BOOT, 0, 0, 0, 0, BOOT, BOOT, 0, 0, 0, 0],
];

/** 矿工-拉拽 (16x16) - 用力拉绳 */
export const MINER_PULL: PixelMap = [
  [0, 0, 0, 0, 0, HAT, HAT, HAT, HAT, HAT, HAT, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, HAT, HAT, HAT_LIGHT, HAT_LIGHT, HAT_LIGHT, HAT, HAT, HAT, 0, 0, 0, 0],
  [0, 0, 0, 0, HAT, HAT, HAT, HAT, HAT, HAT, HAT, HAT, 0, 0, 0, 0],
  [0, 0, 0, 0, HAIR, HAIR, HAIR, HAIR, HAIR, HAIR, HAIR, HAIR, 0, 0, 0, 0],
  [0, 0, 0, 0, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, 0, 0, 0, 0],
  [0, 0, 0, 0, SKIN, EYE, EYE, SKIN, SKIN, EYE, EYE, SKIN, 0, 0, 0, 0],
  [0, 0, 0, 0, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, 0, 0, 0, 0],
  [0, 0, 0, 0, SKIN, SKIN, MOUTH, SKIN, SKIN, MOUTH, SKIN, SKIN, 0, 0, 0, 0],
  [0, 0, 0, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, 0, 0, 0],
  [0, SHIRT, SHIRT, SHIRT, SHIRT_DARK, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT_DARK, SHIRT, SHIRT, SHIRT, SHIRT, 0, 0],
  [0, 0, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, 0, 0],
  [0, 0, 0, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, 0, 0, 0],
  [0, 0, 0, 0, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, 0, 0, 0, 0],
  [0, 0, 0, 0, PANTS, PANTS, 0, 0, 0, 0, PANTS, PANTS, 0, 0, 0, 0],
  [0, 0, 0, 0, PANTS, PANTS, 0, 0, 0, 0, PANTS, PANTS, 0, 0, 0, 0],
  [0, 0, 0, 0, BOOT, BOOT, 0, 0, 0, 0, BOOT, BOOT, 0, 0, 0, 0],
];

/** 矿工-开心 (16x16) - 庆祝表情 */
export const MINER_HAPPY: PixelMap = [
  [0, 0, 0, 0, 0, HAT, HAT, HAT, HAT, HAT, HAT, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, HAT, HAT, HAT_LIGHT, HAT_LIGHT, HAT_LIGHT, HAT, HAT, HAT, 0, 0, 0, 0],
  [0, 0, 0, 0, HAT, HAT, HAT, HAT, HAT, HAT, HAT, HAT, 0, 0, 0, 0],
  [0, 0, 0, 0, HAIR, HAIR, HAIR, HAIR, HAIR, HAIR, HAIR, HAIR, 0, 0, 0, 0],
  [0, 0, 0, 0, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, 0, 0, 0, 0],
  [0, 0, 0, 0, SKIN, WHITE, EYE, SKIN, SKIN, EYE, WHITE, SKIN, 0, 0, 0, 0],
  [0, 0, 0, 0, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, 0, 0, 0, 0],
  [0, 0, 0, 0, SKIN, SKIN, MOUTH, MOUTH, MOUTH, MOUTH, SKIN, SKIN, 0, 0, 0, 0],
  [0, 0, 0, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, 0, 0, 0],
  [0, 0, 0, SHIRT, SHIRT, SHIRT_DARK, SHIRT, SHIRT, SHIRT, SHIRT_DARK, SHIRT, SHIRT, SHIRT, 0, 0, 0],
  [0, 0, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, 0, 0],
  [0, 0, 0, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, 0, 0, 0],
  [0, 0, 0, 0, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, 0, 0, 0, 0],
  [0, 0, 0, 0, PANTS, PANTS, 0, 0, 0, 0, PANTS, PANTS, 0, 0, 0, 0],
  [0, 0, 0, 0, PANTS, PANTS, 0, 0, 0, 0, PANTS, PANTS, 0, 0, 0, 0],
  [0, 0, 0, 0, BOOT, BOOT, 0, 0, 0, 0, BOOT, BOOT, 0, 0, 0, 0],
];

/** 矿工-难过 (16x16) - 沮丧表情 */
export const MINER_SAD: PixelMap = [
  [0, 0, 0, 0, 0, HAT, HAT, HAT, HAT, HAT, HAT, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, HAT, HAT, HAT_LIGHT, HAT_LIGHT, HAT_LIGHT, HAT, HAT, HAT, 0, 0, 0, 0],
  [0, 0, 0, 0, HAT, HAT, HAT, HAT, HAT, HAT, HAT, HAT, 0, 0, 0, 0],
  [0, 0, 0, 0, HAIR, HAIR, HAIR, HAIR, HAIR, HAIR, HAIR, HAIR, 0, 0, 0, 0],
  [0, 0, 0, 0, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, 0, 0, 0, 0],
  [0, 0, 0, 0, EYE, WHITE, SKIN, SKIN, SKIN, SKIN, WHITE, EYE, 0, 0, 0, 0],
  [0, 0, 0, 0, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, 0, 0, 0, 0],
  [0, 0, 0, 0, SKIN, MOUTH, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, 0, 0, 0, 0],
  [0, 0, 0, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, 0, 0, 0],
  [0, 0, 0, SHIRT, SHIRT, SHIRT_DARK, SHIRT, SHIRT, SHIRT, SHIRT_DARK, SHIRT, SHIRT, SHIRT, 0, 0, 0],
  [0, 0, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, 0, 0],
  [0, 0, 0, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, 0, 0, 0],
  [0, 0, 0, 0, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, 0, 0, 0, 0],
  [0, 0, 0, 0, PANTS, PANTS, 0, 0, 0, 0, PANTS, PANTS, 0, 0, 0, 0],
  [0, 0, 0, 0, PANTS, PANTS, 0, 0, 0, 0, PANTS, PANTS, 0, 0, 0, 0],
  [0, 0, 0, 0, BOOT, BOOT, 0, 0, 0, 0, BOOT, BOOT, 0, 0, 0, 0],
];

// ==================== 钩爪精灵 ====================

/** 钩爪 (10x12) - 三叉钩造型 */
export const HOOK_SPRITE: PixelMap = [
  [0, 0, 0, 0, ROPE, ROPE, 0, 0, 0, 0],
  [0, 0, 0, 0, HOOK, HOOK, 0, 0, 0, 0],
  [0, 0, 0, 0, HOOK, HOOK, 0, 0, 0, 0],
  [0, 0, 0, 0, HOOK, HOOK, 0, 0, 0, 0],
  [0, 0, 0, HOOK, HOOK, HOOK, HOOK, 0, 0, 0],
  [0, 0, HOOK, HOOK, HOOK, HOOK, HOOK, HOOK, 0, 0],
  [0, HOOK, HOOK_DARK, 0, HOOK, HOOK, 0, HOOK_DARK, HOOK, 0],
  [HOOK, HOOK_DARK, 0, 0, HOOK, HOOK, 0, 0, HOOK_DARK, HOOK],
  [HOOK, 0, 0, 0, 0, 0, 0, 0, 0, HOOK],
  [0, HOOK, 0, 0, 0, 0, 0, 0, 0, HOOK, 0],
  [0, 0, HOOK, 0, 0, 0, 0, 0, HOOK, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
];

// ==================== 矿物精灵 ====================

/** 小金块 (8x8) */
export const GOLD_SMALL: PixelMap = [
  [0, 0, GOLD, GOLD, GOLD, 0, 0, 0],
  [0, GOLD, GOLD_LIGHT, GOLD_LIGHT, GOLD, GOLD_DARK, 0, 0],
  [GOLD, GOLD_LIGHT, GOLD, GOLD, GOLD, GOLD_DARK, GOLD_DARK, 0],
  [GOLD, GOLD, GOLD, GOLD_LIGHT, GOLD, GOLD_DARK, GOLD_DARK, 0],
  [GOLD_DARK, GOLD, GOLD, GOLD, GOLD, GOLD, GOLD_DARK, 0],
  [0, GOLD_DARK, GOLD, GOLD, GOLD, GOLD_DARK, GOLD_DARK, 0],
  [0, 0, GOLD_DARK, GOLD_DARK, GOLD_DARK, GOLD_DARK, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
];

/** 大金块 (16x16) */
export const GOLD_LARGE: PixelMap = [
  [0, 0, 0, 0, GOLD, GOLD, GOLD, GOLD, GOLD, GOLD, 0, 0, 0, 0, 0, 0],
  [0, 0, GOLD, GOLD, GOLD_LIGHT, GOLD_LIGHT, GOLD, GOLD, GOLD_LIGHT, GOLD, GOLD, GOLD_DARK, 0, 0, 0, 0],
  [0, GOLD, GOLD_LIGHT, GOLD, GOLD, GOLD, GOLD, GOLD_LIGHT, GOLD_LIGHT, GOLD, GOLD, GOLD, GOLD_DARK, 0, 0, 0],
  [GOLD, GOLD_LIGHT, GOLD, GOLD, GOLD_LIGHT, GOLD, GOLD, GOLD, GOLD, GOLD, GOLD, GOLD, GOLD, GOLD_DARK, 0, 0],
  [GOLD, GOLD, GOLD, GOLD_LIGHT, GOLD, GOLD, GOLD, GOLD, GOLD_LIGHT, GOLD, GOLD, GOLD, GOLD, GOLD_DARK, 0, 0],
  [GOLD, GOLD, GOLD, GOLD, GOLD, GOLD, GOLD_LIGHT, GOLD, GOLD, GOLD, GOLD, GOLD_DARK, GOLD_DARK, GOLD_DARK, 0, 0],
  [GOLD_DARK, GOLD, GOLD, GOLD, GOLD, GOLD, GOLD, GOLD, GOLD, GOLD, GOLD, GOLD_DARK, GOLD_DARK, 0, 0, 0],
  [0, GOLD_DARK, GOLD, GOLD, GOLD, GOLD, GOLD, GOLD, GOLD, GOLD, GOLD_DARK, GOLD_DARK, GOLD_DARK, 0, 0, 0],
  [0, GOLD_DARK, GOLD_DARK, GOLD, GOLD, GOLD, GOLD, GOLD, GOLD, GOLD_DARK, GOLD_DARK, GOLD_DARK, 0, 0, 0, 0],
  [0, 0, GOLD_DARK, GOLD_DARK, GOLD, GOLD, GOLD, GOLD, GOLD, GOLD_DARK, GOLD_DARK, 0, 0, 0, 0, 0],
  [0, 0, 0, GOLD_DARK, GOLD_DARK, GOLD, GOLD, GOLD, GOLD_DARK, GOLD_DARK, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, GOLD_DARK, GOLD_DARK, GOLD, GOLD_DARK, GOLD_DARK, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, GOLD_DARK, GOLD_DARK, GOLD_DARK, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
];

/** 钻石 (8x8) */
export const DIAMOND_SPRITE: PixelMap = [
  [0, 0, 0, DIAMOND_LIGHT, DIAMOND_LIGHT, 0, 0, 0],
  [0, 0, DIAMOND_LIGHT, DIAMOND_CLR, DIAMOND_CLR, DIAMOND_LIGHT, 0, 0],
  [0, DIAMOND_LIGHT, DIAMOND_CLR, DIAMOND_CLR, DIAMOND_CLR, DIAMOND_CLR, DIAMOND_DARK, 0],
  [DIAMOND_LIGHT, DIAMOND_CLR, DIAMOND_CLR, DIAMOND_CLR, DIAMOND_CLR, DIAMOND_CLR, DIAMOND_DARK, 0],
  [0, DIAMOND_CLR, DIAMOND_CLR, DIAMOND_CLR, DIAMOND_CLR, DIAMOND_DARK, DIAMOND_DARK, 0],
  [0, 0, DIAMOND_CLR, DIAMOND_CLR, DIAMOND_DARK, DIAMOND_DARK, 0, 0],
  [0, 0, 0, DIAMOND_DARK, DIAMOND_DARK, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
];

/** 石头 (12x12) */
export const STONE_SPRITE: PixelMap = [
  [0, 0, 0, STONE, STONE, STONE, STONE, STONE, STONE, 0, 0, 0],
  [0, 0, STONE_LIGHT, STONE, STONE_LIGHT, STONE, STONE, STONE, STONE_DARK, STONE_DARK, 0, 0],
  [0, STONE_LIGHT, STONE_LIGHT, STONE, STONE, STONE, STONE, STONE, STONE, STONE_DARK, 0, 0],
  [STONE_LIGHT, STONE, STONE, STONE, STONE_LIGHT, STONE, STONE, STONE, STONE, STONE_DARK, STONE_DARK, 0],
  [STONE, STONE, STONE, STONE, STONE, STONE, STONE, STONE, STONE_DARK, STONE_DARK, STONE_DARK, 0],
  [STONE, STONE, STONE, STONE_LIGHT, STONE, STONE, STONE, STONE_DARK, STONE_DARK, STONE_DARK, 0, 0],
  [STONE_DARK, STONE, STONE, STONE, STONE, STONE, STONE, STONE_DARK, STONE_DARK, 0, 0, 0],
  [STONE_DARK, STONE_DARK, STONE, STONE, STONE, STONE, STONE_DARK, STONE_DARK, 0, 0, 0, 0],
  [0, STONE_DARK, STONE_DARK, STONE, STONE, STONE_DARK, STONE_DARK, 0, 0, 0, 0, 0],
  [0, 0, STONE_DARK, STONE_DARK, STONE_DARK, STONE_DARK, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, STONE_DARK, STONE_DARK, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
];

/** 炸弹 (8x8) */
export const BOMB_SPRITE: PixelMap = [
  [0, 0, 0, 0, BOMB_FUSE, 0, 0, 0],
  [0, 0, 0, BOMB_SPARK, BOMB_SPARK, BOMB_FUSE, 0, 0],
  [0, 0, BOMB_BODY, BOMB_BODY, BOMB_BODY, BOMB_BODY, 0, 0],
  [0, BOMB_BODY, BOMB_BODY, BOMB_BODY, BOMB_BODY, BOMB_BODY, BOMB_BODY, 0],
  [0, BOMB_BODY, BOMB_BODY, '#666666', '#666666', BOMB_BODY, BOMB_BODY, 0],
  [0, BOMB_BODY, BOMB_BODY, '#666666', '#666666', BOMB_BODY, BOMB_BODY, 0],
  [0, 0, BOMB_BODY, BOMB_BODY, BOMB_BODY, BOMB_BODY, 0, 0],
  [0, 0, 0, BOMB_BODY, BOMB_BODY, 0, 0, 0],
];

/** 神秘袋 (8x8) */
export const MYSTERY_BAG: PixelMap = [
  [0, 0, 0, BAG_TIE, BAG_TIE, 0, 0, 0],
  [0, 0, BAG_TIE, BAG, BAG, BAG_TIE, 0, 0],
  [0, BAG, BAG, BAG, BAG, BAG, BAG, 0],
  [0, BAG, BAG, '#DAA520', '#DAA520', BAG, BAG, 0],
  [0, BAG, BAG, '#DAA520', '#DAA520', BAG, BAG, 0],
  [0, BAG, BAG, BAG, BAG, BAG, BAG, 0],
  [0, 0, BAG, BAG, BAG, BAG, 0, 0],
  [0, 0, 0, BAG, BAG, 0, 0, 0],
];

/** 骨头 (12x6) */
export const BONE_SPRITE: PixelMap = [
  [0, 0, BONE, BONE, 0, 0, 0, 0, 0, BONE, BONE, 0],
  [BONE, BONE, BONE, BONE, BONE, BONE, BONE, BONE, BONE, BONE, BONE, BONE],
  [BONE, BONE, BONE, BONE, BONE_DARK, BONE_DARK, BONE_DARK, BONE_DARK, BONE, BONE, BONE, BONE],
  [BONE, BONE, BONE, BONE, BONE, BONE, BONE, BONE, BONE, BONE, BONE, BONE],
  [0, 0, BONE, BONE, 0, 0, 0, 0, 0, BONE, BONE, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
];

// ==================== 金币图标 ====================

/** 金币图标 (8x8) */
export const COIN_ICON: PixelMap = [
  [0, 0, GOLD, GOLD, GOLD, GOLD, 0, 0],
  [0, GOLD, GOLD_LIGHT, GOLD_LIGHT, GOLD, GOLD, GOLD_DARK, 0],
  [GOLD, GOLD_LIGHT, GOLD, GOLD, GOLD, GOLD, GOLD_DARK, GOLD_DARK],
  [GOLD, GOLD, GOLD, GOLD, GOLD, GOLD, GOLD_DARK, GOLD_DARK],
  [GOLD_DARK, GOLD, GOLD, GOLD, GOLD, GOLD_DARK, GOLD_DARK, 0],
  [0, GOLD_DARK, GOLD, GOLD, GOLD, GOLD_DARK, 0, 0],
  [0, 0, GOLD_DARK, GOLD_DARK, GOLD_DARK, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
];

// ==================== 所有精灵导出映射 ====================

/** 所有需要预渲染缓存的精灵集合 */
export const ALL_SPRITES: Record<string, PixelMap> = {
  MINER_IDLE,
  MINER_PULL,
  MINER_HAPPY,
  MINER_SAD,
  HOOK_SPRITE,
  GOLD_SMALL,
  GOLD_LARGE,
  DIAMOND_SPRITE,
  STONE_SPRITE,
  BOMB_SPRITE,
  MYSTERY_BAG,
  BONE_SPRITE,
  COIN_ICON,
};
